"""The bridge's exclusive boundary with Kimi Code."""

from .client import KimiServerClient
from .contract import (
    KIMI_ASYNCAPI_PATH,
    KIMI_ASYNCAPI_TITLE,
    KIMI_OPENAPI_PATH,
    KIMI_OPENAPI_TITLE,
    KIMI_REQUIRED_WEB_FLAGS,
    KIMI_REST_OPERATIONS,
    KIMI_SEMANTIC_CONTRACT_VERSION,
    KIMI_WEBSOCKET_PATH,
    KimiCompatibilityProbe,
    KimiContractCheck,
    evaluate_kimi_semantic_contract,
    kimi_semantic_contract,
)
from .supervisor import KimiServerSupervisor, parse_server_startup_line
from .probe import probe_kimi_compatibility
from .types import (
    GoalBudget,
    GoalControl,
    GoalInfo,
    GoalStatus,
    KimiServerAPIError,
    KimiServerAuthenticationError,
    KimiServerError,
    KimiServerProtocolError,
    KimiServerStartupError,
    ModelInfo,
    PendingInteractionKind,
    PermissionMode,
    ServerConnection,
    SessionProfile,
    SessionStatus,
    SessionUsage,
    SkillInfo,
    SkillSource,
    TaskInfo,
    TaskKind,
    TaskStatus,
    ToolInfo,
    ToolSource,
)

__all__ = [
    "GoalBudget",
    "GoalControl",
    "GoalInfo",
    "GoalStatus",
    "KIMI_ASYNCAPI_PATH",
    "KIMI_ASYNCAPI_TITLE",
    "KIMI_OPENAPI_PATH",
    "KIMI_OPENAPI_TITLE",
    "KIMI_REQUIRED_WEB_FLAGS",
    "KIMI_REST_OPERATIONS",
    "KIMI_SEMANTIC_CONTRACT_VERSION",
    "KIMI_WEBSOCKET_PATH",
    "KimiCompatibilityProbe",
    "KimiContractCheck",
    "KimiServerAPIError",
    "KimiServerAuthenticationError",
    "KimiServerClient",
    "KimiServerError",
    "KimiServerProtocolError",
    "KimiServerStartupError",
    "KimiServerSupervisor",
    "ModelInfo",
    "PendingInteractionKind",
    "PermissionMode",
    "ServerConnection",
    "SessionProfile",
    "SessionStatus",
    "SessionUsage",
    "SkillInfo",
    "SkillSource",
    "TaskInfo",
    "TaskKind",
    "TaskStatus",
    "ToolInfo",
    "ToolSource",
    "evaluate_kimi_semantic_contract",
    "kimi_semantic_contract",
    "parse_server_startup_line",
    "probe_kimi_compatibility",
]
