"""Private WeChat iLink control and runtime adapter."""

from .adapter import WeChatAdapter, WeChatRuntimeAPI
from .api import WeChatAPI
from .auth import authorize_with_qr, run_login, run_logout, run_status
from .media import (
    WeChatMediaClient,
    WeChatMediaDependencyError,
    WeChatMediaError,
    WeChatMediaTooLarge,
    cryptography_available,
    require_wechat_media_dependency,
)
from .storage import WeChatRuntimeState, WeChatStorage
from .types import (
    LoginResult,
    WeChatAPIError,
    WeChatAPIResult,
    WeChatAuthenticationExpired,
    WeChatControlError,
    WeChatCredential,
    WeChatCDNMedia,
    WeChatFileItem,
    WeChatImageItem,
    WeChatInboundEvent,
    WeChatMessageItem,
    WeChatPollResult,
    WeChatProtocolError,
    WeChatRetryableError,
    WeChatStorageError,
    WeChatTypingConfig,
    WeChatUploadRequest,
    WeChatUploadedMedia,
    WeChatUploadTarget,
    WeChatUnsupportedOperation,
    WeChatVideoItem,
    WeChatVoiceItem,
)


__all__ = [
    "LoginResult",
    "WeChatAPI",
    "WeChatAPIError",
    "WeChatAPIResult",
    "WeChatAdapter",
    "WeChatAuthenticationExpired",
    "WeChatControlError",
    "WeChatCredential",
    "WeChatCDNMedia",
    "WeChatFileItem",
    "WeChatImageItem",
    "WeChatInboundEvent",
    "WeChatMediaClient",
    "WeChatMediaDependencyError",
    "WeChatMediaError",
    "WeChatMediaTooLarge",
    "WeChatMessageItem",
    "WeChatPollResult",
    "WeChatProtocolError",
    "WeChatRetryableError",
    "WeChatRuntimeAPI",
    "WeChatRuntimeState",
    "WeChatStorage",
    "WeChatStorageError",
    "WeChatTypingConfig",
    "WeChatUploadRequest",
    "WeChatUploadedMedia",
    "WeChatUploadTarget",
    "WeChatUnsupportedOperation",
    "WeChatVideoItem",
    "WeChatVoiceItem",
    "authorize_with_qr",
    "cryptography_available",
    "require_wechat_media_dependency",
    "run_login",
    "run_logout",
    "run_status",
]
